### ISSUE TITLE
AttributeError: 'MediaFileUpload' object has no attribute '_fd'

### ISSUE THREAD

**Issue by Requestedd** [SteBurz/youtube-uploader#1]
Hello! Sorry if something is not clear, I am not an English speaking user, but I liked your code.

I replaced the video paths with my own ("C:\\Vi\\Youtube"), while I also replaced the 19 line in videoDetails.py
In response, I received this error message:

> Uploading file...
> The video with the id ************ was successfully uploaded!
> Exception ignored in: <function MediaFileUpload.__del__ at 0x03BC5B20>
> Traceback (most recent call last):
>   File "C:\Users\Fun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\http.py", line 587, in __del__
>     self._fd.close()
> AttributeError: 'MediaFileUpload' object has no attribute '_fd'
> A retriable error occurred: [Errno 2] No such file or directory: 'C:\\Vi\\Youtube\\None'
> Sleeping %f seconds and then retrying...
> Traceback (most recent call last):
>   File "youtube-uploader.py", line 129, in <module>
>     initialize_upload(youtube, args)
>   File "youtube-uploader.py", line 84, in initialize_upload
>     resumable_upload(insert_request, options)
>   File "youtube-uploader.py", line 121, in resumable_upload
>     print ('Sleeping %f seconds and then retrying...') % sleep_seconds
> TypeError: unsupported operand type(s) for %: 'NoneType' and 'float'
> 

But the video itself loaded successfully!
How can I avoid this error in the future?

After trying a bit to change the paths, I came across a quota issue:
> Uploading file...
> An HTTP error %d occurred:
> %s
> Traceback (most recent call last):
>   File "youtube-uploader.py", line 129, in <module>
>     initialize_upload(youtube, args)
>   File "youtube-uploader.py", line 84, in initialize_upload
>     resumable_upload(insert_request, options)
>   File "youtube-uploader.py", line 95, in resumable_upload
>     status, response = request.next_chunk()
>   File "C:\Users\Fun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "C:\Users\Fun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\googleapiclient\http.py", line 999, in next_chunk
>     raise ResumableUploadError(resp, content)
> googleapiclient.errors.ResumableUploadError: <HttpError 403 "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.">
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "youtube-uploader.py", line 131, in <module>
>     print ('An HTTP error %d occurred:\n%s') % (e.resp.status, e.content)
> TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
> 

If I'm not mistaken, can I solve it if I ask for an increase in the quota in YouTube API?
Have you encountered this?

Thanks for all.

**Comment by SteBurz** [comment]
Hey,
yeah you have to increase the quota for the API, I also ran into this issue. You can upload around 2-3 videos a day until the quota is reached. (depending on how many calls you do in addition (like uploading a thumbnail) to the upload process.)

**Comment by Requestedd** [comment]
Thanks for this.
However, the most important question has not been resolved - do you have any thoughts why the error occurred? How do I fix it?

**Comment by Requestedd** [comment]
The code works like a Swiss watch. The mistake was that I did not put the thumbnail file in the folder.

**Comment by SteBurz** [comment]
Sorry for not getting back, just saw your comment and glad you could solve it by yourself :)
